## Spring Properties
# Service Registered Under this name
spring:
  application:
    name: My-First-Microservice
    
# Discovery Serve Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defalutZone: http://localhost:8761/eureka
      

#Http Server (Tomcat) Port
server:
  port: 9030
        