spring: 

  #Embaded ActiveMQ configuration Example
  activemq:
    broker-url: vm://embadded?broker.persistance=false,useShutDownHook=false
    in-memory: true
    non-blocking-redelivery: true
    packages:
      trust-all: true
      
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      #create-connection-on-startup: true
      enabled: false
      #expiry-timeout: 0
      ideal-timeout: 30000
      max-connections: 1
      maximum-active-session-per-connection: 500
      #reconnect-on-exception: true
      time-between-expiration-check: -1
      use-anonymous-producers: true
    
    #Spring JMS Setting
    jms:
      listener:
        acknowledge-mode: auto
        auto-startup: true
        concurrency: 5
        max-concurrency: 10
      pub-sub-domain: false
      template: 
        default-destination:
        delivery-mode: PERSISTENT
        priority: 100
        qos-enabled: true
        receive-timeout: 1000 
        
        
logging:
  level:
    root: DEBUG
